### ISSUE TITLE
Daemon communication issues with Blade Stealth in 1.1.15 update

### ISSUE THREAD

**Issue by ERobin10** [lah7/polychromatic#118]
Hello, 

So I have updated my Stealth(early 2016) to Fedora 26. Updated all the drivers that are posted on the terrycain site.  The issues is when I open up Polychromatic, upon opening it up it prompts me in red that there is an issue with communicating with the daemon for this device. 

I already tried reinstalling the terrycain drivers for fedora 26 and I have rebooted my device. I'm not sure what i need to do to fix this issue.

**Comment by lah7** [comment]
Some further details will be handy, please run this and paste the output here:
```
polychromatic-controller --print-device-info
```

This is so I know what the daemon is telling the application what is supported.

---------
If you close Polychromatic, clear the log and restart the daemon:
```
rm ~/.local/share/openrazer/logs/razer.log
razer-daemon -r
```

What is the output of this?
```
polychromatic-controller -v
```

And also the output of the daemon log?
```
cat ~/.local/share/openrazer/logs/razer.log
```

This should give a clue to what's going on. :thinking:

**Comment by ERobin10** [comment]
outputs:
polychromatic-controller --print-device-info
 
-------------------------------------------------------------------------------
```
# Device Info
Name: Razer Blade Stealth
Type: keyboard
 
# Device Capabilities
{'name': True, 'type': True, 'firmware_version': True, 'serial': True, 'brightness': True, 'macro_logic': False, 'lighting': True, 'lighting_breath_single': True, 'lighting_breath_dual': True, 'lighting_breath_triple': False, 'lighting_breath_random': True, 'lighting_wave': True, 'lighting_reactive': True, 'lighting_none': True, 'lighting_spectrum': True, 'lighting_static': True, 'lighting_starlight_single': False, 'lighting_starlight_dual': False, 'lighting_starlight_random': False, 'lighting_ripple': False, 'lighting_ripple_random': True, 'lighting_pulsate': False, 'lighting_led_matrix': True, 'lighting_led_single': False, 'lighting_logo': True, 'lighting_logo_active': True, 'lighting_logo_blinking': False, 'lighting_logo_brightness': False, 'lighting_logo_pulsate': False, 'lighting_logo_spectrum': False, 'lighting_logo_static': False, 'lighting_logo_none': False, 'lighting_logo_reactive': False, 'lighting_logo_breath_single': False, 'lighting_logo_breath_dual': False, 'lighting_logo_breath_random': False, 'lighting_scroll': False, 'lighting_scroll_active': False, 'lighting_scroll_blinking': False, 'lighting_scroll_brightness': False, 'lighting_scroll_pulsate': False, 'lighting_scroll_spectrum': False, 'lighting_scroll_static': False, 'lighting_scroll_none': False, 'lighting_scroll_reactive': False, 'lighting_scroll_breath_single': False, 'lighting_scroll_breath_dual': False, 'lighting_scroll_breath_random': False, 'lighting_backlight': False, 'lighting_backlight_active': False, 'game_mode_led': False, 'macro_mode_led': False, 'macro_mode_led_effect': False, 'macro_tartarus_mode_modifier': False}
```
-------------------------------------------------------------------------------
 After running  
rm ~/.local/share/openrazer/logs/razer.log
razer-daemon -r
I got the same error as before. 

After running Polychromatic-controller - v :
```
Verbose enabled
Set scale to: 1.0
Initialised Window.
Loading daemon...
Gathering devices...
 -- Found: Razer Blade Stealth
Loading application profiles...

Set active device: Razer Blade Stealth
Device supports 'brightness'
Device supports 'lighting_logo_active'
There was a problem communicating with the daemon for this device.
Exception: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getLogoActive is not a valid method of interface razer.device.lighting.logo
```

Here is the Daemon output log:
```
2017-08-29 15:35:34 | razer                          | INFO     | Initialising Daemon (v1.1.15). Pid: 3060
2017-08-29 15:35:34 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2012 --------------------- (1532:010D)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2013 --------------------- (1532:011A)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2016 --------------------- (1532:0214)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassic ------------------ (1532:011B)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassicAlternate --------- (1532:010E)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChromaTournamentEdition - (1532:021A)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerExpert ----------------- (1532:0202)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerDeathadderChroma ------------------- (1532:0043)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerDeathadderElite -------------------- (1532:005C)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerFireFly ---------------------------- (1532:0C00)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerImperator -------------------------- (1532:002F)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerKrakenClassic ---------------------- (1532:0501)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaTE ---------------------- (1532:0046)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
2017-08-29 15:35:34 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
2017-08-29 15:35:34 | razer                          | INFO     | Found device.0: 0003:1532:0205.0003
2017-08-29 15:35:34 | razer.device0                  | INFO     | Initialising device.0 RazerBladeStealth
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding getSerial method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.version method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.brightness.getBrightness method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.brightness.setBrightness method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setWave method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setStatic method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setSpectrum method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setReactive method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setNone method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathRandom method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathSingle method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathDual method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setCustom method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.custom.setRippleRandomColour method to DBus
2017-08-29 15:35:34 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoActive method to DBus
2017-08-29 15:35:34 | razer.device0.keymanager       | DEBUG    | Starting KeyWatcher
2017-08-29 15:35:34 | razer.device0                  | INFO     | Putting device into driver mode. Daemon will handle special functionality
2017-08-29 15:35:34 | razer                          | INFO     | Adding razer.devices.getDevices method to DBus
2017-08-29 15:35:34 | razer                          | INFO     | Adding razer.daemon.supportedDevices method to DBus
2017-08-29 15:35:34 | razer                          | INFO     | Adding razer.devices.enableTurnOffOnScreensaver method to DBus
2017-08-29 15:35:34 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
2017-08-29 15:35:34 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
2017-08-29 15:35:34 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
2017-08-29 15:35:34 | razer                          | INFO     | Adding razer.daemon.version method to DBus
2017-08-29 15:35:34 | razer                          | INFO     | Adding razer.daemon.stop method to DBus
2017-08-29 15:35:34 | razer                          | INFO     | Serving DBus
2017-08-29 15:35:52 | razer                          | DEBUG    | DBus called get_serial_list
2017-08-29 15:35:52 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-08-29 15:35:52 | razer.device0                  | DEBUG    | DBus call get_device_name
2017-08-29 15:35:52 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-08-29 15:35:52 | razer.device0                  | DEBUG    | DBus call get_firmware
2017-08-29 15:35:52 | razer.device0                  | DEBUG    | DBus call version
2017-08-29 15:35:52 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-08-29 15:35:52 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-08-29 15:35:53 | razer.device0                  | DEBUG    | DBus call get_brightness
2017-08-29 15:35:53 | razer.device0                  | DEBUG    | DBus call get_brightness
2017-08-29 15:37:16 | razer                          | DEBUG    | DBus called get_serial_list
2017-08-29 15:37:16 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-08-29 15:37:16 | razer.device0                  | DEBUG    | DBus call get_device_name
2017-08-29 15:37:16 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-08-29 15:37:16 | razer.device0                  | DEBUG    | DBus call get_firmware
2017-08-29 15:37:16 | razer.device0                  | DEBUG    | DBus call version
2017-08-29 15:37:16 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-08-29 15:37:16 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-08-29 15:37:17 | razer.device0                  | DEBUG    | DBus call get_brightness
2017-08-29 15:37:17 | razer.device0                  | DEBUG    | DBus call get_brightness


```

**Comment by lah7** [comment]
Oh, the Blade Stealth! Yes, the latest daemon update introduced problems for Blade Stealths after some untested code went into `stable`. It's been fixed in the latest `master` but there has been no updates released since.

[Polychromatic v0.3.10](https://github.com/lah7/polychromatic/releases/tag/v0.3.10) was released to try and prevent these errors from stopping the rest of the interface working, but not enough to mask up the daemon's fault in **1.1.15**.

If you can, you should update the daemon/driver to the latest development branch (as I do not use Fedora, I don't really know what's the best way) **-or-** downgrade to the previous driver/daemon version until there are new packages.

**Comment by ERobin10** [comment]
Since i am running The new Fedora 26, it would consider the packages broken and I could not use the daemon or even upgrade them. I had to re-install everything and do it the new way that is up on the Terrycain site. I'm pretty sure i am running the latest version of the Daemon, as i had to reinstall it.

**Comment by lah7** [comment]
I mean the [`master`](https://github.com/terrycain/razer-drivers/commits/master) "development" version, not the packaged version ([`stable`](https://github.com/terrycain/razer-drivers/commits/stable) - this contains the fault)

Funnily enough, there isn't any reliable instructions to install it manually (it's been discouraged). I've left a message for @terrycain (driver/daemon boss) and @z3ntu (helps package for distros) if there can be another update which *should* clear this issue.

**Comment by ERobin10** [comment]
Sound good!! 
Thank you!

**Comment by lah7** [comment]
All being well, @terrycain will release an update tomorrow.

In the meantime, you could try "dirty" updating just the daemon part with the development files:

```
git clone https://github.com/terrycain/razer-drivers.git --depth=1
```

**Copy:**
* `razer-drivers/daemon/razer_daemon/` to your equivalent `/usr/lib/python3/dist-packages/razer_daemon`
* `razer-drivers/pylib/client` to your equivalent `/usr/lib/python3/dist-packages/razer`
* Then run `razer-daemon -r` and restart Polychromatic.

(The `/usr/lib/` part may differ on Fedora, could be `/usr/local/lib` or not called `dist-packages`)

**Comment by ERobin10** [comment]
I'll give this a try and I will let you know how this "dirty" update goes.

**Comment by z3ntu** [comment]
You can also try https://github.com/terrycain/razer-drivers/wiki/Building-a-package#fedora which should hopefully work (similar instructions worked before but I didn't test them yet)

**Comment by ERobin10** [comment]
@z3ntu  this did the trick i no longer see the error about the daemon.
