### ISSUE TITLE
Application profile editor doesn't show keyboard

### ISSUE THREAD

**Issue by calder** [lah7/polychromatic#126]
![screenshot from 2017-09-27 20-36-46](https://user-images.githubusercontent.com/52222/30948291-bdf0318e-a3c3-11e7-8977-adbee3d62f09.png)

Polychromatic version: Polychromatic v0.3.11-stable
OS version: Ubuntu 16.04 (kernel: 4.10.0-35-generic)

Verbose log output:
```
Verbose enabled
Set scale to: 1.0
Initialised Window.
Version 0.3.11-stable
Loading daemon...
Gathering devices...
 -- Found: Razer Blade (Late 2016)
Loading application profiles...

Set active device: Razer Blade (Late 2016)
Device supports 'brightness'
Device state changed. Refreshing interface.
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 219, in load_changed_cb
    app.page_loaded()
  File "/usr/bin/polychromatic-controller", line 536, in page_loaded
    page_bindings[self.current_page](self)
  File "/usr/bin/polychromatic-controller", line 2567, in profile_editor
    js_exec.exec()
  File "/usr/bin/polychromatic-controller", line 268, in exec
    self.run_javascript(payload)
AttributeError: 'JavaScriptExecutor' object has no attribute 'run_javascript'
```

**Comment by lah7** [comment]
Thanks for spotting that. I'll get a new package released ASAP!

**Comment by calder** [comment]
Thanks @lah7!
