### ISSUE TITLE
Razer Deathadder Chroma isn't supported

### ISSUE THREAD

**Issue by z3ntu** [lah7/polychromatic#41]
For example:

> Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 125, in load_changed_cb
    app.page_loaded()
  File "/usr/bin/polychromatic-controller", line 445, in page_loaded
    self.refresh_device_list()
  File "/usr/bin/polychromatic-controller", line 1393, in refresh_device_list
    app.update_page('#' + selected_ui, "addClass", "active")
TypeError: Can't convert 'NoneType' object to str implicitly
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 112, in title_changed_cb
    app.process_command(title)
  File "/usr/bin/polychromatic-controller", line 825, in process_command
    self.active_device.fx.spectrum()
AttributeError: 'NoneType' object has no attribute 'fx'

Also see https://github.com/terrycain/razer-drivers/issues/23#issuecomment-264954599

Pinging @presianbg

**Comment by terrycain** [comment]
@lah7 You need support for `device.fx.scroll_wheel` and `device.fx.logo` :wink:
