### ISSUE TITLE
polychromatic-controller not finding devices

### ISSUE THREAD

**Issue by sranger** [lah7/polychromatic#42]
When I start the controller, it can't find my keyboard or mouse so I attempted to kill and restart the service using the restart daemon button in the UI and it spams "Unimplemented command:" over and over. A progress bar pops up for loading the daemon and the UI returns with color setting options but still no tabs for my devices. If there's anything I can get for you to debug let me know. I'm running it on Ubuntu GNOME 16.10 and grabbed both ppa's

**Comment by lah7** [comment]
> I attempted to kill and restart the service using the restart daemon button in the UI and it spams "Unimplemented command:" over and over.

Unfortunately, Ubuntu 16.10 ships a version of WebKitGTK [with this bug](https://github.com/lah7/polychromatic/issues/39). that's most likely responsible for that spam. :frowning_face: 

-----------
Which devices are you using?

I just published an update to the PPA ([v0.3.5](https://github.com/lah7/polychromatic/releases/tag/v0.3.5)) which fixed the No Devices screen not appearing. Once you've updated through the Software Updater, please let me know what happens now. Try running with the `-v` flag too:

    polychromatic-controller -v

It will output names of devices the daemon tells us, like this:

```
Gathering Devices...
 -- Found: Razer BlackWidow Chroma
 -- Found: Razer Mamba Tournament Edition
 -- Found: Razer Firefly
```

My guess is that the "No Devices Found" screen will appear, indicating that your keyboard/mouse might not supported by the daemon yet.

**Comment by sranger** [comment]
I just updated from the ppa and rebooted (daemon wouldn't start without a reboot) and I do now get the "No Devices Found" page but it says my mouse is supported and my keyboard might be? I have the BlackWidow Chroma Stealth and the Mamba. I'm assuming there's nothing different between the BlackWidow Stealth and non-Stealth versions but I could be wrong. I checked with lsusb and the ID's do match what's on your device support section.

**Comment by lah7** [comment]
> I have the BlackWidow Chroma Stealth and the Mamba.
>
> I checked with lsusb and the ID's do match what's on your device support section.

It's likely the Razer drivers are not being binded to your devices, so the daemon will not recognise them and thus, Polychromatic won't either. Ubuntu 16.10 and `udev` (which automatically binds drivers) do not seem to be getting along well.

What is the output of these?

    ls /sys/bus/hid/drivers/razerkbd
    ls /sys/bus/hid/drivers/razermouse

You should see this output folders like `0003:1532:0046.0007`. If it does not, they're probably binded to `hid-generic` instead. Try this... the daemon needs restarting afterwards.

    pkill razer-service
    sudo modprobe razerkbd
    sudo modprobe razermouse
    razer-service -F

(`-F` will run the daemon in the foreground, this will output more details that'll help)

---------
I believe this existing issue on the `razer-drivers` repository closes matches the issue here: https://github.com/terrycain/razer-drivers/issues/67

**Comment by sranger** [comment]
the directories contain the following

`bind  module  new_id  uevent  unbind`

the output of running the service in the foreground

`2016-12-16 09:21:46 | razer                          | INFO     | Initialising Daemon (v1.1.2). Pid: 10578
2016-12-16 09:21:46 | razer.screensaver              | INFO     | Initialising DBus Screensaver Thread
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2013 --------------------- (1532:011A)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2016 --------------------- (1532:0214)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChromaTournamentEdition - (1532:021A)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerDeathadderChroma ------------------- (1532:0043)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerFireFly ---------------------------- (1532:0C00)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerImperiator ------------------------- (1532:002F)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaTE ---------------------- (1532:0046)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2016-12-16 09:21:46 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0208)
2016-12-16 09:21:46 | razer                          | INFO     | Adding razer.devices.getDevices method to DBus
2016-12-16 09:21:46 | razer                          | INFO     | Adding razer.devices.enableTurnOffOnScreensaver method to DBus
2016-12-16 09:21:46 | razer                          | INFO     | Adding razer.devices.disableTurnOffOnScreensaver method to DBus
2016-12-16 09:21:46 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
2016-12-16 09:21:46 | razer                          | INFO     | Adding razer.daemon.version method to DBus
2016-12-16 09:21:46 | razer                          | INFO     | Adding razer.daemon.stop method to DBus
2016-12-16 09:21:46 | razer                          | INFO     | Serving DBus
2016-12-16 09:21:48 | razer.screensaver              | INFO     | Initialising DBus screensaver object
2016-12-16 09:21:48 | razer.screensaver              | ERROR    | Caught exception in run loop
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/razer_daemon/misc/screensaver_thread.py", line 123, in run
    screensaver_active = self._dbus_interface.GetActive()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
`

**Comment by lah7** [comment]
The DBus warning is harmless, since the screensaver used in Ubuntu GNOME 16.10 doesn't look like it's supported.

Your devices are not binded to the driver as I suspected, which is why neither the daemon or Polychromatic can do its job.

The `/sys/bus/hid/drivers/razerkbd` directory should have looked similar to this:
```
0003:1532:0203.0004  0003:1532:0203.0006  module  uevent
0003:1532:0203.0005  bind                 new_id  unbind
```

---------
Unfortunately, that's all I know. @terrycain is in charge of the driver/daemon, and has issued this note in the README (I just discovered):

> **No device found**
>
> Those of you on Ubuntu 16.10, some of you on 16.04 and at least some arch users might notice that even though your device is listed as supported it doesnt appear on any of the supporting applications. Udev is not playing ball. Look at [this](https://github.com/terrycain/razer-drivers/issues/67#issuecomment-260419314) comment and run it. Am currently working on a little service that should bind devices and set up the permissions like udev would.

Please [see if this fixes it](https://github.com/terrycain/razer-drivers/issues/67#issuecomment-260419314), and raise further issues over there if not. Thanks!
