### ISSUE TITLE
tray applet crashes when no device is connected

### ISSUE THREAD

**Issue by z3ntu** [lah7/polychromatic#46]
(or when udev doesn't want to bind the device)

```
luca@g550jk /m/h/a/m/razer-drivers> polychromatic-tray-applet 

(polychromatic-tray-applet:12610): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(polychromatic-tray-applet:12610): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(polychromatic-tray-applet:12610): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Using "/usr/share/locale/" or falling back to "en_US" for translations.

Tray applet couldn't be initalised!
Reason: No devices found.
Reloading in 60 seconds.

Tray applet couldn't be initalised!
Reason: No devices found.
Reloading in 60 seconds.
Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 706, in <module>
    indicator.setup()
  File "/usr/bin/polychromatic-tray-applet", line 261, in setup
    self.active_device_status.set_label(devlist[0].name)
IndexError: list index out of range
```

**Comment by z3ntu** [comment]
bump

**Comment by z3ntu** [comment]
Awesome! :)
