### ISSUE TITLE
Open Suse dependencies 

### ISSUE THREAD

**Issue by presianbg** [lah7/polychromatic#63]
Dear All,

I'm trying to run polychromatic under Open Suse Leap 42.2, but I'm unable to satisfy 
dependencies. 

```

Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 25, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib64/python3.4/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available

```

Could you please help me to sort this out, tried to install various packages with webkit in the name, but no luck so far.

Many thanks in advance.

**Comment by lah7** [comment]
According to this [package search](https://software.opensuse.org/search?utf8=%E2%9C%93&q=webkit2&search_devel=false&search_unsupported=false&baseproject=openSUSE%3ALeap%3A42.2), you're probably needing `typelib-1_0-WebKit2-4_0`, which is the equivilant to `gir1.2-WebKit2-4.0` on Ubuntu (these are introspection bindings)

Let us know what other packages you needed to install, then I'll update the README to help other OpenSUSE users. :+1:

**Comment by presianbg** [comment]
Apparently this is the only package i did not tried :(

Works fantastic :+1: 

Many thanks for the support.

**Comment by z3ntu** [comment]
@presianbg Can you please post the output of this command on the openSUSE installation where polychromatic works? `rpm -qa --last | grep -i webkit`

**Comment by z3ntu** [comment]
Okay I think v0.3.9+ shouldn't work with webkit2gtk 2.12.5 because of the commit 5dbd6773333997847a55b99a8c864d570ed744fe . After reverting that one, polychromatic starts fine.

**Comment by presianbg** [comment]
@z3ntu Sorry for being late:

```
typelib-1_0-WebKit2-4_0-2.12.5-1.6.x86_64     Tue 07 Mar 2017 09:15:25 EET
python-webkitgtk-devel-1.1.8-20.3.x86_64      Thu 02 Mar 2017 10:04:42 EET
python-webkitgtk-1.1.8-20.3.x86_64            Thu 02 Mar 2017 10:04:42 EET
webkit2gtk3-devel-2.12.5-1.6.x86_64           Thu 02 Mar 2017 09:58:52 EET
libwebkitgtk-1_0-0-32bit-2.4.11-2.10.x86_64   Thu 02 Mar 2017 09:57:50 EET
libwebkitgtk-3_0-0-32bit-2.4.11-2.10.x86_64   Thu 02 Mar 2017 09:57:49 EET
typelib-1_0-WebKit-3_0-2.4.11-2.10.x86_64     Thu 02 Mar 2017 09:56:04 EET
typelib-1_0-WebKit-1_0-2.4.11-2.10.x86_64     Thu 02 Mar 2017 09:56:04 EET
libwebkitgtk-devel-2.4.11-2.10.x86_64         Thu 02 Mar 2017 09:56:04 EET
libwebkitgtk3-devel-2.4.11-2.10.x86_64        Thu 02 Mar 2017 09:56:04 EET
libQt5WebKitWidgets5-5.6.1-1.31.x86_64        Mon 21 Nov 2016 09:58:39 EET
libQt5WebKit5-imports-5.6.1-1.31.x86_64       Mon 21 Nov 2016 09:58:39 EET
libQt5WebKit5-5.6.1-1.31.x86_64               Mon 21 Nov 2016 09:58:39 EET
libQtWebKit4-4.8.7+2.3.4-4.35.x86_64          Wed 16 Nov 2016 09:11:31 EET
libwebkitgtk3-lang-2.4.11-2.10.noarch         Tue 15 Nov 2016 15:23:31 EET
libwebkitgtk-3_0-0-2.4.11-2.10.x86_64         Tue 15 Nov 2016 15:23:30 EET
libproxy1-pacrunner-webkit-0.4.13-2.1.x86_64  Tue 15 Nov 2016 14:27:08 EET
libwebkit2gtk3-lang-2.12.5-1.6.noarch         Tue 15 Nov 2016 14:14:00 EET
webkit2gtk-4_0-injected-bundles-2.12.5-1.6.x86_64 Tue 15 Nov 2016 14:13:33 EET
libwebkit2gtk-4_0-37-2.12.5-1.6.x86_64        Tue 15 Nov 2016 14:13:16 EET
libwebkitgtk2-lang-2.4.11-2.10.noarch         Tue 15 Nov 2016 14:12:56 EET
libwebkitgtk-1_0-0-2.4.11-2.10.x86_64         Tue 15 Nov 2016 14:12:39 EET
```
