### ISSUE TITLE
Column out off bounds on Application Profile Editor

### ISSUE THREAD

**Issue by ssfernando** [lah7/polychromatic#92]
Hi,

I'm trying to set individual keys with the Application Profile Editor but the app doesn't show the virtual keyboard to assign colors.

I'm running Ubuntu Gnome 17.04 on a Razer Blade early 2017

LOG:

```
Tray applet restarting...
Tray applet reloaded.
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 179, in load_changed_cb
    app.page_loaded()
  File "/usr/bin/polychromatic-controller", line 621, in page_loaded
    self.profiles.send_profile_to_keyboard(self.active_device, profile_data)
  File "/usr/lib/python3/dist-packages/polychromatic/profiles.py", line 145, in send_profile_to_keyboard
    kbd_obj.fx.advanced.matrix[row, col] = data["rows"][str(row)][col]
  File "/usr/lib/python3/dist-packages/razer/client/fx.py", line 839, in __setitem__
    assert 0 <= key[1] < self._cols, "Column out of bounds"
AssertionError: Column out of bounds
2017-05-12 16:44:10 | razer                          | DEBUG    | DBus called get_serial_list
2017-05-12 16:44:10 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-05-12 16:44:10 | razer.device0                  | DEBUG    | DBus call get_device_name
2017-05-12 16:44:10 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-05-12 16:44:10 | razer.device0                  | DEBUG    | DBus call get_firmware
2017-05-12 16:44:10 | razer.device0                  | DEBUG    | DBus call version
2017-05-12 16:44:10 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-05-12 16:44:10 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-05-12 16:44:10 | razer.device0                  | DEBUG    | DBus call get_brightness

(polychromatic-tray-applet:26382): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

![image](https://cloud.githubusercontent.com/assets/802541/26006053/fb359d8e-3732-11e7-99dc-91f948347ad6.png)

**Comment by lah7** [comment]
It should work with the latest `master` or daily packages (when they're next built).

However, as there isn't a SVG for the Razer Blade, you will see a full-key BlackWidow keyboard. It's possible further errors may occur if you specify keys outside your device's matrix.

Profiles will be the focus for the next release. :+1:
